### ISSUE TITLE
Netta database generate massive memleaks from version 2.3

### ISSUE THREAD

**Issue by DanielNoga** [nette/database#64] opened 2015-04-06 12:28 UTC
Starting from Nette Database 2.3 there are present memleaks with Nette database.

When I run this method 1000x it consumes hundreds of MB: 
$context->table('table_name')->insert(['col1' => $val1])->getPrimary(); 

When I run these two methods 1000x it consumes tens of MB:
$context->query('INSERT INTO table_name (col1) VALUES (?)', $val1);
$context->getInsertId();

When I run these three methods 1000x it consumes a few MB:
$prep = $context->getConnection()->getPdo()->query('INSERT INTO table_name (col1) VALUES (?)');
$prep->execute($val1);
$context->getConnection()->getPdo()->lastInsertId();

Tested on PHP 5.6.5 and 5.6.1 on two different computers

**Comment by DanielNoga** [comment] 2015-04-16 12:59
Nobody has severe issues with new Nette database 2.3?

**Comment by pavolbiely** [comment] 2015-04-23 14:37
I can confirm. We had to downgrade back to 2.2.

PHP version 5.4.24.

**Comment by dg** [comment] 2015-05-03 16:37
I am unable to reproduce it (Apache/2.4.5 (Win32) PHP/5.4.31, MySQL)

**Comment by tomasstrejcek** [comment] 2015-05-03 19:06
php5-fpm or cli in php 5.6.7(8)

with this config:

```
database:
	default:
		dsn: 'mysql:host=%database.host%;dbname=%database.dbName%'
		user: %database.user%
		password: %database.password%
		options:      [PDO::MYSQL_ATTR_COMPRESS = true, lazy: yes]
		debugger:     true        # panel v debugger baru
		explain:      true        # explain dotazů v debugger bar
		conventions:  discovered  # nebo static nebo vaší jméno třídy, výchozí je discovered
		autowired:    true
```

**Comment by dg** [comment] 2015-05-04 13:06
1000x INSERT, memory_get_peak_usage() returns ~11 MB, even garbage collector is disabled. Are you using something special, like Xdebug or etc.?

**Comment by norbe** [comment] 2015-10-30 14:43
Are you using kdyby/events? Today I have found similar problem caused by event debugger..

**Comment by DanielNoga** [comment] 2015-11-28 19:56
Yes, we use kdyby/events

**Comment by Unlink** [comment] 2015-11-28 20:09
@DanielNoga try turn off events debugger

```NEON
events:
	debugger: off
```

**Comment by Unlink** [comment] 2016-06-02 14:43
@dg this is not relevant to ntdb, could you close it?

**Closed** 2016-06-02 14:53 UTC
